import { async } from "@firebase/util";
import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";
import { getProviders, getSession, useSession } from "next-auth/react";
import Login from "../components/Login";
import Modal from "../components/Modal";
import { modalState } from "../atoms/modalAtom";
import { useRecoilState } from "recoil";

export default function Home({ trendingResults, followResults, providers }) {
  //this checks if someone signed in
  const { data: session } = useSession();
  const [isOpen, setIsOpen] = useRecoilState(modalState);

  //this line will not return the code below if there is not an active session
  //it will instead return a login page for the provider
  if (!session) return <Login providers={providers} />;

  return (
    <div className={styles.container}>
      <Head>
        <title>Moontweet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/stars-and-moon_icon-icons.com_54250.ico" />
      </Head>

      <main className="bg- min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
        {isOpen && <Modal />}
      </main>
    </div>
  );
}

//serversideprop is for information that is dynamic, it is constantly changing

export async function getServerSideProps(context) {

  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {

      providers,
      session,
    },
  };
}
